language: go

sudo: false

matrix:
  include:
  - go: "1.13.x"
    arch: amd64
  - go: "1.14.x"
    arch: amd64
  - go: "1.15.x"
    arch: amd64
  - go: "1.13.x"
    arch: ppc64le
  - go: "1.14.x"
    arch: ppc64le
  - go: "1.15.x"
    arch: ppc64le
    
    env:
      - GO111MODULE=off
  - go: "1.11.x"
    env:
      - GO111MODULE=on
  - go: "tip"
    env:
      - GO111MODULE=off
  - go: "tip"
    env:
      - GO111MODULE=on
  allow_failures:
    - go: "tip"

install: make deps

script: make ci-test
